name: FizzBuzz package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . .[tests] .[lint]
      - name: Lint with pylint
        run: |
          pylint src tests
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest --cov-report html --cov=src tests/
